name: JNS
favicon: null
layout_spectrum: 0.2780098938383162
typography_spectrum: 0.9145209970884025
title: JNS IT Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.10628192336298525
  lightness: 0.2631342043168843
  saturation: 0.06815227144397795
  rhythmicContrast: 0.3007027506828308
purpose: []
